### ISSUE TITLE
Won't let me add feeds and won't load.

### ISSUE THREAD

**Issue by tommxcd** [Suzie97/Communique#23] opened 2022-06-03 22:47 UTC
## Describe the bug
I open the app and it keeps loading and saying it's "Offline". It won't let me add any feeds.

## To Reproduce
I just opened the app.

## Expected behavior
I thought It would prompt me to add feeds.

## Screenshots
![offline](https://user-images.githubusercontent.com/66445023/171963335-15e5c9eb-a569-4115-b39c-ba1c4bf2c684.png)

## Platform Information
I am currently using GeckoLinux Rolling with Pantheon Desktop

**Comment by Suzie97** [comment] 2022-06-03 23:23
Hey @tommxcd, thank you for the bug report. I'm closing this as a duplicate of #9. For now, you can click on the Preferences button at the top right portion of the toolbar and then click on Change Account.

**Closed by Suzie97** 2022-06-03 23:23 UTC
