### ISSUE TITLE
Podcast player

### ISSUE THREAD

**Issue by MakeGnomeWebFaster** [Suzie97/Communique#16] opened 2022-01-23 12:23 UTC
## Problem

Currently, Communique does not support playing podcasts.

## Proposal

Many modern RSS feed readers also support podcasts, including Nextcloud News, which you can sign in on Communique.

## Prior Art
(List any relevant examples of how others have implemented this feature)
These feed readers can do this;
- [NewsFlash](https://flathub.org/apps/details/com.gitlab.newsflash)
- [Liferea](https://flathub.org/apps/details/net.sourceforge.liferea)

**Comment by Suzie97** [comment] 2022-01-23 12:52
Hey @MakeGnomeWebFaster thanks for reporting. This issue has been already discussed here, you can check it out and reopen the existing issue if you want to share anything.

Closing this as a duplicate of #12

**Closed** 2022-01-23 12:52 UTC
